<?php


namespace App;

use App\Traits\Encryptable;
use Illuminate\Database\Eloquent\Model;
use Eloquent;
use function foo\func;

/**
 * Class Texts
 * @package App
 * @mixin Eloquent
 * @property string text
 * @property boolean share
 * @property boolean contribute_to_science
 * @property integer user_id
 * @property string voice
 * @property string where_from
 * @property boolean hide
 * @property string privacy_update_date
 * @property integer rank
 */
class Texts extends Model
{
    use Encryptable;
    protected $table ='text';
    protected $fillable = [
        'hide',
        'rank'
    ];
    protected $encryptable = [
        'text',
    ];
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::updating(function (self $model) {
            if ($model->isDirty('hide') || $model->isDirty('share'))
            {
                $model->setAttribute('privacy_update_date', date('Y-m-d').' '.date('H:m:i'));
            }
        });
        static::saving(function (self  $model) {
            $model->encrypted  = 1;
        });
    }
}
